# Generated by Django 3.0.8 on 2020-07-04 17:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityperiod',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 17, 46, 6, 771081, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='activityperiod',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 17, 46, 6, 771081, tzinfo=utc)),
        ),
    ]
